int wildcmp(char *s1, char *s2);
int is_palindrome(char *s);
int recursion3(char c[], int d, int j);
int is_prime_number(int n);
int recursion2(int n, int j);
int recursion(int n, int j);
int _sqrt_recursion(int n);
int _pow_recursion(int x, int y);
int factorial(int n);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
